version: "3.1"

services:
  gateway:
    image: "nginx:1.15.8-alpine"
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    depends_on:
      - "server1"

  server1:
    image: "kddc/athleets:server-latest"
    ports:
      - "8080:8080"
    environment:
      - "MONGODB_URI=mongodb://mongo:27017"
      - "MONGODB_DATABASE_NAME=athleets"
    depends_on:
      - "mongo"

  mongo:
    image: "mongo:3.6"
    ports:
      - "27017:27017"
    volumes:
      - "mongo:/data/db"
    restart: "unless-stopped"
#      - "MONGO_INITDB_ROOT_USERNAME=root"
#      - "MONGO_INITDB_ROOT_PASSWORD=root"

volumes:
  mongo:
    driver: "local"